import { useParams } from "react-router-dom";
import { apiClient } from "../../api/client";
import { useQuery } from "@tanstack/react-query";
import { PdfExportActions, type StoredExport } from "../../components/records/PdfExportActions";
import { extractErrorMessage } from "../../hooks/useWorkflowAction";

function when(value: string): string {
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value;
  return date.toLocaleString();
}

/** Permission-checked lookup for one export. Shows identity and checksum, not the record body. */
export function VerifyExportPage() {
  const { exportId = "" } = useParams();
  const query = useQuery({
    queryKey: ["pdf-export", exportId],
    enabled: exportId.startsWith("exp_"),
    queryFn: async () => (await apiClient.get<StoredExport>(`/pdf-exports/${exportId}`)).data,
    retry: false,
  });

  if (!exportId.startsWith("exp_")) return <p className="text-sm text-muted-foreground">That export id is not valid.</p>;
  if (query.isLoading) return <p className="text-sm text-muted-foreground">Checking this export…</p>;
  if (query.isError) return <p className="text-sm text-destructive">{extractErrorMessage(query.error, "You can't open this record.")}</p>;
  const row = query.data;
  if (!row) return <p className="text-sm text-muted-foreground">That export was not found.</p>;

  return (
    <div className="mx-auto flex w-full max-w-3xl flex-col gap-4">
      <h1 className="text-2xl font-semibold">PDF export</h1>
      <dl className="grid grid-cols-[10rem_1fr] gap-x-3 gap-y-2 text-sm">
        <dt className="text-muted-foreground">Record</dt>
        <dd>{row.recordNumber || "—"}</dd>
        <dt className="text-muted-foreground">Revision</dt>
        <dd>{row.revision || "—"}</dd>
        <dt className="text-muted-foreground">Status</dt>
        <dd>{row.status || "—"}</dd>
        <dt className="text-muted-foreground">Exported</dt>
        <dd>{when(row.exportedAt)}</dd>
        <dt className="text-muted-foreground">Checksum</dt>
        <dd>{row.checksumMatches ? "Matches the stored file" : "Does not match the stored file"}</dd>
        <dt className="text-muted-foreground">Export id</dt>
        <dd className="break-all">{row.exportId}</dd>
        <dt className="text-muted-foreground">Generated by</dt>
        <dd>{row.generatedBy || "—"}</dd>
        <dt className="text-muted-foreground">SHA-256</dt>
        <dd className="break-all font-mono text-xs">{row.sha256}</dd>
        <dt className="text-muted-foreground">Size</dt>
        <dd>{row.size} bytes</dd>
        <dt className="text-muted-foreground">MIME</dt>
        <dd>{row.mime}</dd>
        <dt className="text-muted-foreground">Renderer</dt>
        <dd>{row.renderer}</dd>
      </dl>
      <PdfExportActions exportId={row.exportId} entityType={row.entityType} entityId={row.entityId} />
    </div>
  );
}
