import { Router } from "express";
import { authRouter } from "../modules/auth/auth.routes.js";
import { usersRouter } from "../modules/users/users.routes.js";
import { rolesRouter } from "../modules/roles/roles.routes.js";
import { documentsRouter } from "../modules/documents/documents.routes.js";
import { documentFoldersRouter } from "../modules/document-folders/document-folders.routes.js";
import { ncrRouter } from "../modules/ncr/ncr.routes.js";
import { capaRouter } from "../modules/capa/capa.routes.js";
import { eightDRouter } from "../modules/eight-d/eight-d.routes.js";
import { auditsRouter } from "../modules/audits/audits.routes.js";
import { trainingRouter } from "../modules/training/training.routes.js";
import { changeRouter } from "../modules/change/change.routes.js";
import { riskRouter } from "../modules/risk/risk.routes.js";
import { ppapRouter } from "../modules/ppap/ppap.routes.js";
import { qualityRouter } from "../modules/quality/quality.routes.js";
import { supplierRouter } from "../modules/supplier/supplier.routes.js";
import { calibrationRouter } from "../modules/calibration/calibration.routes.js";
import { complaintsRouter } from "../modules/complaints/complaints.routes.js";
import { workflowRouter } from "../modules/workflow/workflow.routes.js";
import { aiRouter } from "../modules/ai/ai.routes.js";
import { digitalTwinRouter } from "../modules/digital-twin/digital-twin.routes.js";
import { auditTrailRouter } from "../modules/audit-trail/audit-trail.routes.js";
import { formsRouter } from "../modules/forms/forms.routes.js";
import { platformRouter } from "../modules/platform/platform.routes.js";
import { navRouter } from "../modules/nav/nav.routes.js";
import { inventoryRouter } from "../modules/inventory/inventory.routes.js";
import { erpRouter } from "../modules/erp/erp.routes.js";
import { erpRequisitionsRouter } from "../modules/erp/erpRequisitions.routes.js";
import { tenantRouter } from "../modules/tenant/tenant.routes.js";
import { searchRouter } from "../modules/search/search.routes.js";
import { rmaRouter } from "../modules/rma/rma.routes.js";
import { workOrdersRouter } from "../modules/work-orders/workOrders.routes.js";
import { onboardingRouter } from "../modules/onboarding/onboarding.routes.js";
import { feasibilityRouter } from "../modules/feasibility/feasibility.routes.js";
import { salesRouter } from "../modules/sales/sales.routes.js";
import { customersRouter } from "../modules/customers/customers.routes.js";
import { documentChangeRequestsRouter } from "../modules/document-change-requests/documentChangeRequests.routes.js";
import { qmsFormsRouter } from "../modules/qms-forms/qmsForms.routes.js";
import { scarFormsRouter } from "../modules/scar-forms/scarForms.routes.js";
import { qualityInspectionReportsRouter } from "../modules/quality-inspection-reports/qualityInspectionReports.routes.js";
import { settingsRouter } from "../modules/settings/settings.routes.js";
import { attachmentsRouter } from "../modules/attachments/attachments.routes.js";
import { warrantyRouter } from "../modules/warranty/warranty.routes.js";
import { supplierPortalRouter } from "../modules/supplier-portal/supplierPortal.routes.js";

export const apiRouter = Router();

apiRouter.use("/auth", authRouter);
apiRouter.use("/users", usersRouter);
apiRouter.use("/roles", rolesRouter);
apiRouter.use("/documents", documentsRouter);
apiRouter.use("/document-folders", documentFoldersRouter);
apiRouter.use("/ncr", ncrRouter);
apiRouter.use("/capa", capaRouter);
apiRouter.use("/8d", eightDRouter);
apiRouter.use("/audits", auditsRouter);
apiRouter.use("/training", trainingRouter);
apiRouter.use("/change", changeRouter);
apiRouter.use("/risk", riskRouter);
apiRouter.use("/ppap", ppapRouter);
apiRouter.use("/quality", qualityRouter);
apiRouter.use("/suppliers", supplierRouter);
apiRouter.use("/equipment", calibrationRouter);
apiRouter.use("/complaints", complaintsRouter);
apiRouter.use("/workflow", workflowRouter);
apiRouter.use("/ai", aiRouter);
apiRouter.use("/digital-twin", digitalTwinRouter);
apiRouter.use("/audit-trail", auditTrailRouter);
apiRouter.use("/forms", formsRouter);
apiRouter.use("/platform", platformRouter);
apiRouter.use("/nav", navRouter);
apiRouter.use("/inventory", inventoryRouter);
// Registered before /erp: a more specific prefix match must come first so
// /erp/requisitions/* is handled by its own router (a different department
// gate — see erpRequisitions.routes.ts's own comment) instead of falling
// into erpRouter's blanket "erp" gate.
apiRouter.use("/erp/requisitions", erpRequisitionsRouter);
apiRouter.use("/erp", erpRouter);
apiRouter.use("/tenant", tenantRouter);
apiRouter.use("/search", searchRouter);
apiRouter.use("/rma", rmaRouter);
apiRouter.use("/work-orders", workOrdersRouter);
apiRouter.use("/onboarding", onboardingRouter);
apiRouter.use("/feasibility", feasibilityRouter);
apiRouter.use("/sales", salesRouter);
apiRouter.use("/customers", customersRouter);
apiRouter.use("/document-change-requests", documentChangeRequestsRouter);
apiRouter.use("/qms-forms", qmsFormsRouter);
apiRouter.use("/scar-forms", scarFormsRouter);
apiRouter.use("/quality-inspection-reports", qualityInspectionReportsRouter);
apiRouter.use("/settings", settingsRouter);
apiRouter.use("/attachments", attachmentsRouter);
apiRouter.use("/warranty", warrantyRouter);
apiRouter.use("/supplier-portal", supplierPortalRouter);
