-- Module-specific RBAC build (2026-09-16): the automated Supplier RMA
-- Request event trail keeps its exact data and behavior, only its name
-- moves -- "rma_log" is freed for the new, manually-maintained RMA Log
-- register added in the next migration. A hand-written custom migration
-- (drizzle-kit generate --custom) rather than an auto-generated one: a
-- plain RENAME is unambiguous and lossless, where drizzle-kit's own
-- interactive rename-vs-drop-and-create resolver can't run headlessly in
-- this environment.
--
-- Deliberately renames ONLY the table, not its indexes: rma_log_rma_idx
-- and rma_log_tenant_id_idx were never created by a drizzle-kit migration
-- at all — they're hand-written in post-migrate/indexes.sql (see that
-- file's own header comment on why), which runs AFTER every drizzle
-- migration, including this one. On a truly fresh database (CI, a new
-- deploy) those indexes don't exist yet at this point in the run, so an
-- ALTER INDEX ... RENAME here would fail outright. indexes.sql already
-- creates them under their new, correct names (rma_activity_log_rma_idx /
-- rma_activity_log_tenant_id_idx) the moment it runs next — nothing here
-- needs to rename them.
ALTER TABLE "rma_log" RENAME TO "rma_activity_log";
