import { Route, Navigate } from "react-router-dom";
import { NotFoundPage } from "./NotFoundPage";
import { homeKind } from "../lib/opsLanguage";
import { blankFormsFolderHref } from "../lib/folderBrowse";
import { FRM_NCR_PATH } from "../lib/qualityEntry";
import { useCurrentUser } from "../hooks/useAuth";
import {
  AdminAiSettingsPage,
  AdminAiUsagePage,
  AdminApiDocsPage,
  AuditLogPage,
  AdminCompanyAiConfigPage,
  AdminCompanyBrandingPage,
  AdminCompanySettingsPage,
  AdminCompanyTemplatesPage,
  AdminConsoleHomePage,
  AdminConsoleLayout,
  AdminDataExportPage,
  AdminDigitalTwinSetupPage,
  AdminPlantsPage,
  AdminQualitySettingsPage,
  AdminReceivingInventorySettingsPage,
  AdminSsoPage,
  AdminSupplierSettingsPage,
  AdminSystemHealthPage,
  AdminImportPage,
  AdminUsersRolesPage,
  AiInsightsPage,
  AuditDetailPage,
  AuditsPage,
  StartBlankFormPage,
  CalendarPage,
  CapaDetailPage,
  CapaListPage,
  ChangeDetailPage,
  ChangePage,
  ControlledDocumentPage,
  CrarDetailPage,
  CrarListPage,
  DashboardPage,
  DigitalTwinPage,
  DocumentCategoryPage,
  DocumentChangeRequestDetailPage,
  DocumentChangeRequestsPage,
  DocumentDetailPage,
  DocumentsPage,
  EightDDetailPage,
  EightDPage,
  ErpPresetEditorPage,
  ErpPresetsListPage,
  ErpSyncErrorsPage,
  ValidationReportDetailPage,
  IsoFormListPage,
  IsoFormDetailPage,
  MasterEquipmentListPage,
  MasterDocumentListPage,
  FormImportPage,
  EmployeeTrainingHistoryPage,
  EquipmentDetailPage,
  FeasibilityDetailPage,
  FeasibilityPage,
  FolderExplorerPage,
  FormFolderDetailPage,
  FormFoldersPage,
  GeneralUploadsPage,
  HomePage,
  ManagementSystemPage,
  NavigationSettingsPage,
  NcrListPage,
  NcrWorkspacePage,
  NotificationsPage,
  ParetoAnalysisPage,
  PpapDetailPage,
  PpapListPage,
  QmsFormRecordPage,
  QmsFormTypePage,
  QmsFormsLibraryPage,
  CsaFaiListPage,
  CsaFaiRecordPage,
  FuelPumpFaiListPage,
  FuelPumpFaiRecordPage,
  FaiPlanPage,
  FaiPullPage,
  FaiQueuePage,
  FaiRecordPage,
  FaiSourcesPage,
  QualityInspectionReportDetailPage,
  QualityInspectionReportsPage,
  QuarantineDetailPage,
  QuarantinePage,
  ReportingHubPage,
  VerifyExportPage,
  RetiredModulePage,
  RiskDashboardPage,
  RiskDetailPage,
  RiskPage,
  RmaDetailPage,
  RolesPermissionsPage,
  ScarFormDetailPage,
  ScarFormsPage,
  SettingsPage,
  SupplierDetailPage,
  SupplierPortalHome,
  SuppliersPage,
  TrainingDetailPage,
  TrainingPage,
  WarrantyClaimDetail,
  WarrantyClaimsList,
  WarrantyDashboard,
  WorkOrderDetailPage,
  WorkerDetailPage,
  WorkersPage,
  WorkflowBuilderPage,
  WorkflowCanvasPage,
  CalibrationPage,
} from "./pages";

function HomeRoute() {
  const user = useCurrentUser();
  return homeKind(user?.roleName) === "lead" ? <DashboardPage /> : <HomePage />;
}

/** Page routes under AppLayout. Called again for the right split pane so each pane gets its own element tree. */
export function workspaceRouteElements() {
  return [
    <Route key="/" path="/" element={<HomeRoute />} />,
    <Route key="/home" path="/home" element={<HomePage />} />,
    <Route key="/blank-forms" path="/blank-forms" element={<Navigate to={blankFormsFolderHref()} replace />} />,
    <Route key="/blank-forms/start" path="/blank-forms/start/:formKey" element={<StartBlankFormPage />} />,
    <Route key="/form-folders" path="/form-folders" element={<FormFoldersPage />} />,
    <Route key="/form-folders/:formKey" path="/form-folders/:formKey" element={<FormFolderDetailPage />} />,
    <Route key="/calendar" path="/calendar" element={<CalendarPage />} />,
    <Route key="/audit-log" path="/audit-log" element={<AuditLogPage />} />,
    <Route key="/ncr" path="/ncr" element={<NcrListPage />} />,
    <Route key="/ncr/:id" path="/ncr/:id" element={<NcrWorkspacePage />} />,
    <Route key="/capa" path="/capa" element={<CapaListPage />} />,
    <Route key="/capa/:id" path="/capa/:id" element={<CapaDetailPage />} />,
    <Route key="/8d" path="/8d" element={<EightDPage />} />,
    <Route key="/8d/:id" path="/8d/:id" element={<EightDDetailPage />} />,
    <Route key="/validation-reports/:id" path="/validation-reports/:id" element={<ValidationReportDetailPage />} />,
    <Route key="/iso-forms/record/:id" path="/iso-forms/record/:id" element={<IsoFormDetailPage />} />,
    <Route key="/iso-forms/:formKey" path="/iso-forms/:formKey" element={<IsoFormListPage />} />,
    <Route key="/audits" path="/audits" element={<AuditsPage />} />,
    <Route key="/audits/:id" path="/audits/:id" element={<AuditDetailPage />} />,
    <Route key="/quality" path="/quality" element={<Navigate to={FRM_NCR_PATH} replace />} />,
    <Route key="/quality/:id" path="/quality/:id" element={<Navigate to={FRM_NCR_PATH} replace />} />,
    <Route key="/folders/:category" path="/folders/:category" element={<DocumentCategoryPage />} />,
    <Route key="/documents" path="/documents" element={<DocumentsPage />} />,
    <Route key="/documents/master-list" path="/documents/master-list" element={<MasterDocumentListPage />} />,
    <Route key="/documents/import" path="/documents/import" element={<FormImportPage />} />,
    <Route key="/documents/folders" path="/documents/folders" element={<FolderExplorerPage />} />,
    <Route key="/documents/uploads" path="/documents/uploads" element={<GeneralUploadsPage />} />,
    <Route key="/documents/:id" path="/documents/:id" element={<DocumentDetailPage />} />,
    <Route key="/training" path="/training" element={<TrainingPage />} />,
    <Route key="/training/employee/:userId" path="/training/employee/:userId" element={<EmployeeTrainingHistoryPage />} />,
    <Route key="/training/:id" path="/training/:id" element={<TrainingDetailPage />} />,
    <Route key="/workers" path="/workers" element={<WorkersPage />} />,
    <Route key="/workers/:id" path="/workers/:id" element={<WorkerDetailPage />} />,
    <Route key="/change" path="/change" element={<ChangePage />} />,
    <Route key="/change/:id" path="/change/:id" element={<ChangeDetailPage />} />,
    <Route key="/risk" path="/risk" element={<RiskPage />} />,
    <Route key="/risk/dashboard" path="/risk/dashboard" element={<RiskDashboardPage />} />,
    <Route key="/risk/:id" path="/risk/:id" element={<RiskDetailPage />} />,
    <Route key="/feasibility" path="/feasibility" element={<FeasibilityPage />} />,
    <Route key="/feasibility/:id" path="/feasibility/:id" element={<FeasibilityDetailPage />} />,
    <Route key="/sales" path="/sales" element={<Navigate to="/" replace />} />,
    <Route key="/sales/dashboard" path="/sales/dashboard" element={<Navigate to="/" replace />} />,
    <Route key="/sales/:id" path="/sales/:id" element={<Navigate to="/" replace />} />,
    <Route key="/customers" path="/customers" element={<Navigate to="/" replace />} />,
    <Route key="/customers/dashboard" path="/customers/dashboard" element={<Navigate to="/" replace />} />,
    <Route key="/customers/:id" path="/customers/:id" element={<Navigate to="/" replace />} />,
    <Route key="/document-change-requests" path="/document-change-requests" element={<DocumentChangeRequestsPage />} />,
    <Route key="/document-change-requests/:id" path="/document-change-requests/:id" element={<DocumentChangeRequestDetailPage />} />,
    <Route key="/qms-forms" path="/qms-forms" element={<QmsFormsLibraryPage />} />,
    <Route key="/qms-forms/:formType" path="/qms-forms/:formType" element={<QmsFormTypePage />} />,
    <Route key="/qms-forms/:formType/:id" path="/qms-forms/:formType/:id" element={<QmsFormRecordPage />} />,
    <Route key="/scar-forms" path="/scar-forms" element={<ScarFormsPage />} />,
    <Route key="/scar-forms/:id" path="/scar-forms/:id" element={<ScarFormDetailPage />} />,
    <Route key="/fai/csa" path="/fai/csa" element={<CsaFaiListPage />} />,
    <Route key="/fai/csa/:id" path="/fai/csa/:id" element={<CsaFaiRecordPage />} />,
    <Route key="/fai/fuel-pump" path="/fai/fuel-pump" element={<FuelPumpFaiListPage />} />,
    <Route key="/fai/fuel-pump/:id" path="/fai/fuel-pump/:id" element={<FuelPumpFaiRecordPage />} />,
    <Route key="/fai" path="/fai" element={<FaiQueuePage />} />,
    <Route key="/fai/plans/new" path="/fai/plans/new" element={<FaiPlanPage />} />,
    <Route key="/fai/plans/:id" path="/fai/plans/:id" element={<FaiPlanPage />} />,
    <Route key="/fai/records/:id" path="/fai/records/:id" element={<FaiRecordPage />} />,
    <Route key="/fai/sources" path="/fai/sources" element={<FaiSourcesPage />} />,
    <Route key="/fai/pull" path="/fai/pull" element={<FaiPullPage />} />,
    <Route key="/quality-inspection-reports" path="/quality-inspection-reports" element={<QualityInspectionReportsPage />} />,
    <Route key="/quality-inspection-reports/:id" path="/quality-inspection-reports/:id" element={<QualityInspectionReportDetailPage />} />,
    <Route key="/ppap" path="/ppap" element={<PpapListPage />} />,
    <Route key="/ppap/:id" path="/ppap/:id" element={<PpapDetailPage />} />,
    <Route key="/production-logs" path="/production-logs" element={<RetiredModulePage name="Production" />} />,
    <Route key="/management-system" path="/management-system" element={<ManagementSystemPage />} />,
    <Route
      key="/management-system/management-review"
      path="/management-system/management-review"
      element={<ControlledDocumentPage basePath="/management-review" formType="management_review" title="Management Review" noun="management review" description="Management system performance evaluation — strategic core review inputs and the action items they produce." />}
    />,
    <Route
      key="/management-system/context"
      path="/management-system/context"
      element={<ControlledDocumentPage basePath="/context" formType="context_of_organization" title="Context of the Organization" noun="context analysis" description="ISO 9001 clause 4.1 — internal strengths and weaknesses, external opportunities and threats, by interested party." />}
    />,
    <Route key="/pareto" path="/pareto" element={<ParetoAnalysisPage />} />,
    <Route key="/suppliers/new" path="/suppliers/new" element={<SuppliersPage />} />,
    <Route key="/suppliers" path="/suppliers" element={<SuppliersPage />} />,
    <Route key="/suppliers/:id" path="/suppliers/:id" element={<SupplierDetailPage />} />,
    <Route key="/calibration" path="/calibration" element={<CalibrationPage />} />,
    <Route key="/calibration/master-list" path="/calibration/master-list" element={<MasterEquipmentListPage />} />,
    <Route key="/calibration/:id" path="/calibration/:id" element={<EquipmentDetailPage />} />,
    <Route key="/quarantine" path="/quarantine" element={<QuarantinePage />} />,
    <Route key="/quarantine/:id" path="/quarantine/:id" element={<QuarantineDetailPage />} />,
    <Route key="/complaints" path="/complaints" element={<Navigate to={FRM_NCR_PATH} replace />} />,
    <Route key="/complaints/:id" path="/complaints/:id" element={<Navigate to={FRM_NCR_PATH} replace />} />,
    <Route key="/inventory/*" path="/inventory/*" element={<RetiredModulePage name="Inventory" />} />,
    <Route key="/erp/*" path="/erp/*" element={<RetiredModulePage name="ERP" />} />,
    <Route key="/erp" path="/erp" element={<RetiredModulePage name="ERP" />} />,
    <Route key="/rma" path="/rma" element={<RetiredModulePage name="RMA" />} />,
    <Route key="/rma/:id" path="/rma/:id" element={<RmaDetailPage />} />,
    <Route key="/warranty" path="/warranty" element={<WarrantyClaimsList />} />,
    <Route key="/warranty/dashboard" path="/warranty/dashboard" element={<WarrantyDashboard />} />,
    <Route key="/warranty/:id" path="/warranty/:id" element={<WarrantyClaimDetail />} />,
    <Route key="/crar" path="/crar" element={<CrarListPage />} />,
    <Route key="/crar/:id" path="/crar/:id" element={<CrarDetailPage />} />,
    <Route key="/rma-activity-log" path="/rma-activity-log" element={<RetiredModulePage name="RMA activity" />} />,
    <Route key="/rma-log/*" path="/rma-log/*" element={<RetiredModulePage name="RMA log" />} />,
    <Route key="/rma-log" path="/rma-log" element={<RetiredModulePage name="RMA log" />} />,
    <Route key="/supplier-portal" path="/supplier-portal" element={<SupplierPortalHome />} />,
    <Route key="/work-orders" path="/work-orders" element={<RetiredModulePage name="Work orders" />} />,
    <Route key="/work-orders/:id" path="/work-orders/:id" element={<WorkOrderDetailPage />} />,
    <Route key="/onboarding" path="/onboarding" element={<Navigate to="/settings" replace />} />,
    <Route key="/workflow" path="/workflow" element={<WorkflowBuilderPage />} />,
    <Route key="/workflow/:id" path="/workflow/:id" element={<WorkflowCanvasPage />} />,
    <Route key="/ai" path="/ai" element={<AiInsightsPage />} />,
    <Route key="/digital-twin" path="/digital-twin" element={<DigitalTwinPage />} />,
    <Route key="/settings" path="/settings" element={<SettingsPage />} />,
    <Route key="/settings/erp/presets" path="/settings/erp/presets" element={<ErpPresetsListPage />} />,
    <Route key="/settings/erp/presets/:id" path="/settings/erp/presets/:id" element={<ErpPresetEditorPage />} />,
    <Route key="/settings/erp/sync-errors" path="/settings/erp/sync-errors" element={<ErpSyncErrorsPage />} />,
    <Route key="/settings/navigation" path="/settings/navigation" element={<NavigationSettingsPage />} />,
    <Route key="/admin/company-ai" path="/admin/company-ai" element={<AdminCompanyAiConfigPage />} />,
    <Route key="/admin/ai-usage" path="/admin/ai-usage" element={<AdminAiUsagePage />} />,
    <Route key="/admin" path="/admin" element={<AdminConsoleLayout />}>
      <Route index element={<AdminConsoleHomePage />} />
      <Route path="users" element={<AdminUsersRolesPage />} />
      <Route path="import" element={<AdminImportPage />} />
      <Route path="plants" element={<AdminPlantsPage />} />
      <Route path="roles-permissions" element={<RolesPermissionsPage />} />
      <Route path="ai-settings" element={<AdminAiSettingsPage />} />
      <Route path="supplier-settings" element={<AdminSupplierSettingsPage />} />
      <Route path="quality-settings" element={<AdminQualitySettingsPage />} />
      <Route path="receiving-inventory-settings" element={<AdminReceivingInventorySettingsPage />} />
      <Route path="system-health" element={<AdminSystemHealthPage />} />
      <Route path="api-docs" element={<AdminApiDocsPage />} />
      <Route path="company-settings" element={<AdminCompanySettingsPage />} />
      <Route path="sso" element={<AdminSsoPage />} />
      <Route path="data-export" element={<AdminDataExportPage />} />
      <Route path="company-branding" element={<AdminCompanyBrandingPage />} />
      <Route path="company-templates" element={<AdminCompanyTemplatesPage />} />
      <Route path="digital-twin" element={<AdminDigitalTwinSetupPage />} />
      <Route path="*" element={<NotFoundPage />} />
    </Route>,
    <Route key="/reporting" path="/reporting" element={<ReportingHubPage />} />,
    <Route key="/verify/:exportId" path="/verify/:exportId" element={<VerifyExportPage />} />,
    <Route key="/reports" path="/reports" element={<Navigate to="/reporting" replace />} />,
    <Route key="/notifications" path="/notifications" element={<NotificationsPage />} />,
    <Route key="*" path="*" element={<NotFoundPage />} />,
  ];
}
