/**
 * Default document folder taxonomy -- 7 departments, seeded for every tenant
 * the first time GET /document-folders finds none yet (see document-folders.controller.ts).
 * Derived from the user's own 7 uploaded department folder/subfolder lists; every
 * subfolder that had no documents in the source was dropped rather than kept as an
 * empty stub, per the user's own instruction.
 */
export interface DefaultFolderSeed {
  name: string;
  children: DefaultFolderSeed[];
}

export const DEFAULT_DOCUMENT_FOLDERS: DefaultFolderSeed[] = [
  {
    name: "Engineering",
    children: [
      { name: "Design & Development", children: [{ name: "Design Inputs", children: [] }, { name: "Design Outputs", children: [] }, { name: "Design Reviews", children: [] }, { name: "DFMEA (Design FMEA)", children: [] }, { name: "Risk Analysis", children: [] }, { name: "Prototypes / Samples", children: [] }, { name: "Design Verification", children: [] }, { name: "Design Validation", children: [] }, { name: "DHF (Design History File)", children: [] }] },
      { name: "Engineering Change Control", children: [{ name: "Engineering Change Requests (ECR)", children: [] }, { name: "Engineering Change Orders (ECO)", children: [] }, { name: "Change Impact Assessments", children: [] }, { name: "Revision Logs", children: [] }, { name: "Archived/Obsolete Designs", children: [] }] },
      { name: "Specifications & Standards", children: [{ name: "Product Specifications", children: [] }, { name: "Material Specifications", children: [] }, { name: "Component Specs", children: [] }, { name: "GD&T / Tolerance Standards", children: [] }, { name: "Workmanship Standards", children: [] }, { name: "Engineering Standards", children: [] }, { name: "Customer-Specific Requirements (CSR)", children: [] }] },
      { name: "Drawings & CAD", children: [{ name: "Mechanical Drawings", children: [] }, { name: "Electrical Schematics", children: [] }, { name: "PCB Layouts", children: [] }, { name: "Tooling Drawings", children: [] }, { name: "Fixture/Jig Drawings", children: [] }, { name: "CAD Models (2D/3D)", children: [] }, { name: "Revision Archive", children: [] }] },
      { name: "Calibration & Measurement", children: [{ name: "Calibration Procedures", children: [] }, { name: "Calibration Certificates", children: [] }, { name: "Equipment Master List", children: [] }, { name: "Gage R&R Studies", children: [] }, { name: "MSA (Measurement System Analysis)", children: [] }] },
      { name: "Manufacturing Engineering", children: [{ name: "Process Flow Diagrams", children: [] }, { name: "PFMEA", children: [] }, { name: "Control Plans", children: [] }, { name: "Work Instructions (Engineering-owned)", children: [] }, { name: "Tooling & Fixture Documentation", children: [] }, { name: "Capability Studies (Cp/Cpk)", children: [] }, { name: "Run @ Rate Documentation", children: [] }, { name: "Process Validation", children: [] }] },
      { name: "Supplier Engineering", children: [{ name: "Supplier Specifications", children: [] }, { name: "Supplier Drawings", children: [] }, { name: "Supplier Change Notifications", children: [] }, { name: "Supplier PPAP Submissions", children: [] }, { name: "Supplier Capability Studies", children: [] }, { name: "Supplier Engineering Reports", children: [] }] },
      { name: "Technical Records", children: [{ name: "Failure Analysis Reports", children: [] }, { name: "Root Cause Engineering Reports", children: [] }, { name: "Field Issue Engineering Analysis", children: [] }, { name: "Reliability Studies", children: [] }, { name: "Engineering Support for CAR/PAR", children: [] }, { name: "MRB Engineering Decisions", children: [] }] },
    ],
  },
  {
    name: "Quality",
    children: [
      { name: "Quality Manual & Policies", children: [{ name: "Quality Manual", children: [] }, { name: "Quality Policy", children: [] }, { name: "Mission / Vision / Values", children: [] }, { name: "Organizational Chart", children: [] }, { name: "Scope of QMS", children: [] }, { name: "Exclusions & Justifications", children: [] }] },
      { name: "Procedures (SOPs)", children: [{ name: "Document Control Procedure", children: [] }, { name: "Record Control Procedure", children: [] }, { name: "Training Procedure", children: [] }, { name: "Calibration Procedure", children: [] }, { name: "Internal Audit Procedure", children: [] }, { name: "Control of Nonconforming Product", children: [] }, { name: "Corrective Action Procedure", children: [] }, { name: "Preventive Action Procedure", children: [] }, { name: "Supplier Quality Procedure", children: [] }, { name: "Risk Management Procedure", children: [] }, { name: "Change Control Procedure", children: [] }, { name: "Complaint Handling Procedure", children: [] }, { name: "Engineering Change Procedure", children: [] }, { name: "Production Control Procedure", children: [] }] },
      { name: "Work Instructions", children: [{ name: "Department Work Instructions", children: [] }, { name: "Process Work Instructions", children: [] }, { name: "Equipment Work Instructions", children: [] }, { name: "Inspection Work Instructions", children: [] }, { name: "Packaging Work Instructions", children: [] }, { name: "Shipping Work Instructions", children: [] }] },
      { name: "Forms & Templates", children: [{ name: "NCR Form", children: [] }, { name: "8D Form", children: [] }, { name: "CAPA Form", children: [] }, { name: "SCAR Form", children: [] }, { name: "Audit Checklist", children: [] }, { name: "Calibration Form", children: [] }, { name: "Training Record", children: [] }, { name: "Change Request Form", children: [] }, { name: "Engineering Change Order Form", children: [] }, { name: "Inspection Forms", children: [] }, { name: "Receiving Inspection Form", children: [] }, { name: "Final Inspection Form", children: [] }] },
      { name: "Records", children: [{ name: "NCR Records", children: [] }, { name: "8D Records", children: [] }, { name: "CAPA Records", children: [] }, { name: "SCAR Records", children: [] }, { name: "Audit Records", children: [] }, { name: "Calibration Certificates", children: [] }, { name: "Training Records", children: [] }, { name: "Inspection Records", children: [] }, { name: "Production Records", children: [] }, { name: "Customer Complaint Records", children: [] }, { name: "Supplier Performance Records", children: [] }, { name: "Change Control Records", children: [] }, { name: "Engineering Change Records", children: [] }] },
      { name: "Audits", children: [{ name: "Internal Audit Schedule", children: [] }, { name: "Internal Audit Reports", children: [] }, { name: "External Audit Reports", children: [] }, { name: "Audit Findings", children: [] }, { name: "Audit Follow-Up", children: [] }, { name: "Audit Evidence", children: [] }] },
      { name: "Corrective & Preventive Actions", children: [{ name: "CAPA Reports", children: [] }, { name: "Root Cause Analysis", children: [] }, { name: "Containment Actions", children: [] }, { name: "Corrective Actions", children: [] }, { name: "Preventive Actions", children: [] }, { name: "Effectiveness Checks", children: [] }, { name: "Closure Documentation", children: [] }] },
      { name: "Nonconformance Management", children: [{ name: "Quarantine Material", children: [] }, { name: "WIP Hold / Quarantine", children: [] }, { name: "Incoming NCRs", children: [] }] },
      { name: "Supplier Quality", children: [{ name: "Supplier Audits", children: [] }, { name: "Supplier NCR", children: [] }, { name: "Supplier SCAR", children: [] }, { name: "Supplier Scorecards", children: [] }] },
      { name: "Calibration & Equipment", children: [{ name: "Calibration Procedures", children: [] }, { name: "Calibration Certificates", children: [] }, { name: "Equipment Master List", children: [] }, { name: "Equipment Maintenance Records", children: [] }, { name: "Gage R&R", children: [] }, { name: "MSA Studies", children: [] }] },
      { name: "Risk Management", children: [{ name: "PFMEA", children: [] }, { name: "DFMEA", children: [] }, { name: "Process Flow Diagrams", children: [] }, { name: "Control Plans", children: [] }, { name: "Risk Assessments", children: [] }, { name: "Hazard Analysis", children: [] }] },
      { name: "Customer Quality", children: [{ name: "Complaint NCRs", children: [] }, { name: "Complaint 8Ds", children: [] }, { name: "Complaint Corrective Actions", children: [] }, { name: "Complaint Closure Documentation", children: [] }, { name: "RMA Requests", children: [] }, { name: "RMA Approvals", children: [] }, { name: "Returned Product Inspection", children: [] }, { name: "RMA NCRs", children: [] }, { name: "RMA Root Cause Analysis", children: [] }, { name: "RMA Credit / Replacement Documentation", children: [] }] },
      { name: "Production & Inspection", children: [{ name: "First Article Inspection (FAI)", children: [] }, { name: "In-Process Inspection", children: [] }, { name: "Final Inspection", children: [] }, { name: "SPC Charts", children: [] }, { name: "Process Capability Studies", children: [] }, { name: "Measurement Records", children: [] }, { name: "Sampling Plans", children: [] }, { name: "Inspection Checklists", children: [] }, { name: "Defect Trend Analysis", children: [] }, { name: "Pareto Charts", children: [] }, { name: "Control Charts", children: [] }, { name: "Production Quality KPIs", children: [] }, { name: "Corrective Actions (Production-related)", children: [] }] },
      { name: "Document Control", children: [{ name: "Master Document List", children: [] }, { name: "Revision History", children: [] }, { name: "Obsolete Documents", children: [] }, { name: "Controlled Document Archive", children: [] }] },
      { name: "Training & Competency", children: [{ name: "Training Matrix", children: [] }, { name: "Training Records", children: [] }, { name: "Competency Assessments", children: [] }, { name: "Certifications", children: [] }, { name: "Qualification Records", children: [] }] },
    ],
  },
  {
    name: "Production",
    children: [
      { name: "Production Planning", children: [{ name: "Production Schedule (Read-Only)", children: [] }, { name: "Work Orders / Packages", children: [] }, { name: "Job Travelers / Routers", children: [] }, { name: "Material Requirements", children: [] }, { name: "Production Forecasts (Read-Only)", children: [] }, { name: "Capacity Planning", children: [] }] },
      { name: "Process Documentation", children: [{ name: "Standard Operating Procedures (Production SOP's only)", children: [] }, { name: "Work Instructions (Engineer-released copies only)", children: [] }, { name: "Setup Sheets", children: [] }, { name: "Tooling Instructions", children: [] }] },
      { name: "Workstations / Cells", children: [{ name: "Workstation / Line Station Setup", children: [] }, { name: "Assembly Line", children: [] }, { name: "Packaging Area", children: [] }, { name: "Cell Work Instructions", children: [] }, { name: "Cell Setup Sheets", children: [] }, { name: "Cell Tooling Lists", children: [] }, { name: "Cell Inspection Criteria", children: [] }] },
      { name: "Material & Inventory", children: [{ name: "Raw Material Receiving", children: [] }, { name: "Material Certifications (Quality?)", children: [] }, { name: "Lot Traceability (Quality?)", children: [] }, { name: "Material Handling Instructions", children: [] }, { name: "FIFO Records", children: [] }] },
      { name: "Equipment & Tooling", children: [{ name: "Machine Setup Sheets", children: [] }, { name: "Tooling Lists", children: [] }, { name: "Fixture Documentation", children: [] }, { name: "Preventive Maintenance Records", children: [] }, { name: "Machine Capability Studies (Cp/Cpk)", children: [] }, { name: "Tool Life Tracking", children: [] }] },
      { name: "Production Records", children: [{ name: "Production Control Records", children: [] }] },
      { name: "Nonconformance & Rework", children: [{ name: "Production NCRs (Create NCR Reports Only)", children: [] }, { name: "Rework Instructions", children: [] }, { name: "Rework Records", children: [] }, { name: "Scrap Reports (Quality?)", children: [] }] },
      { name: "Training & Competency", children: [{ name: "Operator Training Records", children: [] }, { name: "Machine Qualification", children: [] }, { name: "Cross-Training Matrix", children: [] }, { name: "Safety Training", children: [] }, { name: "Production Certifications", children: [] }] },
      { name: "Safety & Compliance", children: [{ name: "Safety Procedures", children: [] }, { name: "PPE Requirements", children: [] }, { name: "Incident Reports", children: [] }, { name: "Safety Audits", children: [] }, { name: "Lockout/Tagout Procedures", children: [] }] },
      { name: "Packaging & Shipping", children: [{ name: "Packaging Instructions", children: [] }, { name: "Labeling Requirements (Shipping?)", children: [] }, { name: "Final Packaging Inspection", children: [] }, { name: "Customer-Specific Packaging Requirements", children: [] }] },
    ],
  },
  {
    name: "Material Management",
    children: [
      { name: "Material Receiving", children: [{ name: "Receiving Logs", children: [] }, { name: "Receiving Inspection Forms (Quality?)", children: [] }, { name: "Supplier Packing Lists", children: [] }, { name: "Delivery Receipts", children: [] }, { name: "Material Certifications (MTRs, COCs)", children: [] }, { name: "Incoming Inspection (Create NCRs Only)", children: [] }] },
      { name: "Raw Materials", children: [{ name: "Raw Material Inventory", children: [] }, { name: "Raw Material Specifications", children: [] }, { name: "Material Safety Data Sheets (MSDS/SDS)", children: [] }, { name: "Material Handling Instructions", children: [] }, { name: "Storage Requirements", children: [] }, { name: "Shelf-Life Tracking", children: [] }] },
      { name: "Components & Parts", children: [{ name: "Component Inventory", children: [] }, { name: "Component Specifications", children: [] }, { name: "Approved Component List", children: [] }, { name: "Component Revision History (Engineering?)", children: [] }, { name: "Component Traceability Records (Quality/Engineering?)", children: [] }] },
      { name: "WIP", children: [{ name: "WIP Inventory", children: [] }, { name: "WIP Movement Logs", children: [] }, { name: "WIP Traceability", children: [] }, { name: "WIP Rework Records", children: [] }] },
      { name: "Finished Goods", children: [{ name: "Finished Goods Inventory", children: [] }, { name: "Finished Goods Inspection Records", children: [] }] },
      { name: "Inventory Control", children: [{ name: "Inventory Adjustments", children: [] }, { name: "Cycle Count Records", children: [] }, { name: "Physical Inventory Reports", children: [] }, { name: "FIFO/LIFO Tracking", children: [] }, { name: "Lot Control Records", children: [] }, { name: "Material Shortage Reports", children: [] }] },
      { name: "Traceability", children: [{ name: "Lot Traceability", children: [] }, { name: "Heat Number Tracking", children: [] }, { name: "Serial Number Tracking", children: [] }, { name: "Batch Records", children: [] }, { name: "Material Usage Logs", children: [] }, { name: "Backward/Forward Traceability Reports", children: [] }] },
      { name: "Material Certifications", children: [{ name: "MTRs (Material Test Reports)", children: [] }, { name: "COCs (Certificates of Conformance)", children: [] }, { name: "Chemical Composition Reports", children: [] }, { name: "Mechanical Property Reports", children: [] }, { name: "Supplier Certification Packages", children: [] }, { name: "Material Certifications (MTR, COC) — from Shipping & Receiving", children: [] }] },
      { name: "Storage & Handling", children: [{ name: "Storage Maps", children: [] }, { name: "Material Handling Procedures", children: [] }, { name: "Environmental Requirements", children: [] }, { name: "Temperature/Humidity Logs", children: [] }, { name: "Hazardous Material Handling", children: [] }] },
      { name: "Material Planning", children: [{ name: "Material Forecasts", children: [] }, { name: "Material Requirements Planning (MRP)", children: [] }, { name: "Purchase Requests", children: [] }, { name: "Purchase Orders", children: [] }, { name: "Lead Time Tracking", children: [] }, { name: "Supplier Delivery Performance", children: [] }] },
    ],
  },
  {
    name: "Shipping & Receiving",
    children: [
      { name: "Incoming Receiving", children: [{ name: "Receiving Logs", children: [] }, { name: "Receiving Inspection Reports", children: [] }, { name: "Supplier Packing Slips", children: [] }, { name: "Bills of Lading (Inbound)", children: [] }, { name: "Delivery Receipts", children: [] }, { name: "Supplier Delivery Issues", children: [] }] },
      { name: "Incoming Inspection", children: [{ name: "Inspection Checklists", children: [] }, { name: "Sampling Plans", children: [] }, { name: "First Article Receiving Inspection", children: [] }, { name: "Dimensional Reports", children: [] }, { name: "Visual Inspection Records", children: [] }, { name: "Photos / Evidence", children: [] }, { name: "Inspection Failures (Create NCR's Only)", children: [] }, { name: "Supplier Nonconformance Reports (Create NCR's Only)", children: [] }] },
      { name: "Raw Material Intake", children: [{ name: "Raw Material Receiving", children: [] }, { name: "Raw Material Identification", children: [] }, { name: "Lot Number Assignment", children: [] }, { name: "Heat Number Tracking", children: [] }, { name: "Raw Material Storage Requirements", children: [] }, { name: "SDS / Hazardous Material Sheets", children: [] }] },
      { name: "WIP Receiving / Transfers", children: [{ name: "WIP Transfer Logs", children: [] }, { name: "WIP Receiving Records", children: [] }, { name: "WIP Hold / Quarantine (duplicate ref, see Quality)", children: [] }, { name: "WIP Rework Records", children: [] }, { name: "Internal Transfer Documentation", children: [] }] },
      { name: "Outgoing Shipping", children: [{ name: "Shipping Logs", children: [] }, { name: "Bills of Lading (Outbound)", children: [] }, { name: "Packing Lists", children: [] }, { name: "Customer Shipping Requirements", children: [] }, { name: "Shipping Labels", children: [] }, { name: "Freight Documentation", children: [] }, { name: "Export Documentation (if applicable)", children: [] }] },
      { name: "Final Inspection for Shipment", children: [{ name: "Final Inspection Reports", children: [] }, { name: "Final Dimensional Checks", children: [] }, { name: "Functional Test Results", children: [] }, { name: "Photos of Final Product", children: [] }, { name: "Packaging Verification", children: [] }, { name: "Customer-Specific Final Inspection", children: [] }] },
      { name: "Packaging", children: [{ name: "Packaging Instructions", children: [] }, { name: "Packaging Specifications", children: [] }, { name: "Customer Packaging Requirements", children: [] }, { name: "Labeling Requirements", children: [] }, { name: "Packaging Material Inventory", children: [] }, { name: "Packaging NCRs (Create Only)", children: [] }] },
      { name: "Traceability", children: [{ name: "Lot Traceability Records", children: [] }, { name: "Serial Number Tracking", children: [] }, { name: "Batch Records", children: [] }, { name: "Backward/Forward Traceability", children: [] }, { name: "Shipment Traceability Reports", children: [] }] },
      { name: "Customer Delivery", children: [{ name: "Customer Delivery Receipts", children: [] }, { name: "Customer Delivery Issues", children: [] }, { name: "Delivery Performance Metrics", children: [] }, { name: "Customer Complaints (Shipping-related)", children: [] }] },
      { name: "Freight & Logistics", children: [{ name: "Carrier Information", children: [] }, { name: "Freight Quotes", children: [] }, { name: "Freight Damage Reports", children: [] }, { name: "Freight NCRs (Create Only)", children: [] }, { name: "Delivery Performance (Carrier)", children: [] }, { name: "Shipping Cost Analysis", children: [] }] },
    ],
  },
  {
    name: "Purchasing",
    children: [
      { name: "Purchase Orders", children: [{ name: "Open Purchase Orders", children: [] }, { name: "Closed Purchase Orders", children: [] }, { name: "Cancelled Purchase Orders", children: [] }, { name: "Blanket Purchase Orders", children: [] }, { name: "PO Revision History", children: [] }, { name: "PO Change Requests", children: [] }] },
      { name: "Supplier Management", children: [{ name: "Approved Supplier List (ASL)", children: [] }, { name: "Supplier Onboarding Documents", children: [] }, { name: "Supplier Agreements / Contracts", children: [] }, { name: "Supplier Certifications", children: [] }, { name: "Supplier Scorecards", children: [] }, { name: "Supplier Performance Reports", children: [] }, { name: "Supplier Change Notifications", children: [] }] },
      { name: "Quotes & Sourcing", children: [{ name: "RFQs (Requests for Quote)", children: [] }, { name: "Supplier Quotes", children: [] }, { name: "Cost Breakdowns", children: [] }, { name: "Quote Comparison Sheets", children: [] }, { name: "Sourcing Decisions", children: [] }, { name: "Supplier Selection Records", children: [] }] },
      { name: "Purchasing Records", children: [{ name: "Purchase Requisitions", children: [] }, { name: "Purchase Approvals", children: [] }, { name: "Purchase Justifications", children: [] }, { name: "Procurement Logs", children: [] }, { name: "Cost Tracking", children: [] }, { name: "Budget vs Actual Reports", children: [] }] },
      { name: "Material Certifications", children: [{ name: "Material Test Reports (MTRs)", children: [] }, { name: "Certificates of Conformance (COCs)", children: [] }, { name: "Supplier Material Certifications", children: [] }, { name: "Chemical/Mechanical Property Reports", children: [] }] },
      { name: "Inventory & Material Planning", children: [{ name: "Material Requirements Planning (MRP)", children: [] }, { name: "Forecasting", children: [] }, { name: "Lead Time Tracking", children: [] }, { name: "Supplier Delivery Performance", children: [] }, { name: "Shortage Reports", children: [] }, { name: "Safety Stock Calculations", children: [] }] },
      { name: "Compliance & Documentation", children: [{ name: "Purchasing Procedure (SOP)", children: [] }, { name: "Supplier Terms & Conditions", children: [] }, { name: "Regulatory Compliance Docs", children: [] }, { name: "Conflict Minerals Documentation", children: [] }, { name: "RoHS/REACH Certificates", children: [] }, { name: "ITAR/EAR Documentation (if applicable)", children: [] }] },
      { name: "Cost & Financial", children: [{ name: "Cost Analysis Reports", children: [] }, { name: "Price Change Notifications", children: [] }, { name: "Cost Reduction Projects", children: [] }, { name: "Annual Supplier Pricing Agreements", children: [] }] },
    ],
  },
  {
    name: "Customer Service",
    children: [
      { name: "Customer Accounts", children: [{ name: "Customer Profiles", children: [] }, { name: "Customer Contact Information", children: [] }, { name: "Customer Agreements / Contracts", children: [] }, { name: "Customer Terms & Conditions", children: [] }, { name: "Customer-Specific Requirements (CSR)", children: [] }, { name: "Approved Customer List", children: [] }] },
      { name: "Customer Orders", children: [{ name: "Sales Orders", children: [] }, { name: "Order Confirmations", children: [] }, { name: "Order Changes / Revisions", children: [] }, { name: "Customer Forecasts", children: [] }, { name: "Blanket Orders", children: [] }, { name: "Customer PO History", children: [] }] },
      { name: "Customer Communication", children: [{ name: "General Communication Logs", children: [] }, { name: "Meeting Notes", children: [] }, { name: "Email Correspondence", children: [] }, { name: "Customer Requests", children: [] }, { name: "Customer Feedback", children: [] }, { name: "Customer Escalations", children: [] }] },
      { name: "Customer Complaints", children: [{ name: "Complaint Reports", children: [] }, { name: "Complaint Investigation Records", children: [] }] },
    ],
  },
  {
    name: "Sales and Marketing",
    children: [
      { name: "Sales Management", children: [{ name: "Sales Strategy", children: [] }, { name: "Sales Goals & KPIs", children: [] }, { name: "Territory Plans", children: [] }, { name: "Sales Playbooks", children: [] }, { name: "Sales Policies", children: [] }, { name: "Sales Training Materials", children: [] }] },
      { name: "Quotes & Proposals", children: [{ name: "RFQs (Requests for Quote)", children: [] }, { name: "Quote Revision History", children: [] }, { name: "Proposal Templates", children: [] }, { name: "Submitted Proposals", children: [] }, { name: "Pricing Sheets", children: [] }, { name: "Product Sheets", children: [] }] },
      { name: "Contracts & Agreements", children: [{ name: "Customer Contracts", children: [] }, { name: "NDAs", children: [] }, { name: "Service Agreements", children: [] }, { name: "Pricing Agreements", children: [] }, { name: "Renewal Agreements", children: [] }, { name: "Contract Change Requests", children: [] }] },
      { name: "Product Information", children: [{ name: "Product Catalogs", children: [] }, { name: "Product Specifications", children: [] }, { name: "Product Feature Sheets", children: [] }, { name: "Product Launch Materials", children: [] }, { name: "Product Training Guides", children: [] }] },
      { name: "Customer Data / Requirements", children: [{ name: "Customer-Specific Requirements (CSR)", children: [] }, { name: "Technical Requirements", children: [] }, { name: "Packaging Requirements", children: [] }, { name: "Delivery Requirements", children: [] }, { name: "Revision Requirements", children: [] }, { name: "Customer Standards", children: [] }, { name: "Drawing Requirements", children: [] }, { name: "Email Correspondence", children: [] }, { name: "Customer Quotes", children: [] }, { name: "VOC (Voice of Customer) Data", children: [] }, { name: "Customer Satisfaction Reports", children: [] }, { name: "Customer Surveys", children: [] }, { name: "Sales Orders", children: [] }, { name: "Order Confirmations", children: [] }, { name: "Order Changes", children: [] }, { name: "Blanket Orders", children: [] }, { name: "Customer PO History", children: [] }, { name: "Meeting Notes", children: [] }, { name: "Customer Requests", children: [] }, { name: "Customer Feedback", children: [] }] },
    ],
  },
];
