/** Keep these strings aligned with services/api/src/modules/change-requests/ecrTemplate.ts. */

export const ECR_STRUCTURE_CERTIFY = "I certify that I am authorized to change the engineering change request template.";

export const ECR_LABEL_DEFAULTS: Record<string, string> = {
  workflowStatus: "Workflow Status:",
  section1: "SECTION 1: IDENTIFICATION",
  dateOfRequest: "Date of Request:",
  requestedBy: "Requested By:",
  partNumbers: "Part Number(s) Affected:",
  currentRevision: "Current Revision:",
  job: "Job / Project:",
  newRevision: "New Revision (Proposed):",
  section2: "SECTION 2: CHANGE DETAILS",
  changeType: "Type of Change:",
  changeSupplier: "Supplier Request",
  changeCost: "Cost Reduction",
  changeQuality: "Quality Improvement",
  changeDimensional: "Dimensional Correction",
  description: "Description of Change (Current vs. Proposed):",
  reason: "Reason / Explanation:",
  drawingUpdate: "Drawing Update Required?",
  drawingNote: "If YES attach draft drawing.",
  section3: "SECTION 3: ENGINEERING REVIEW & RISK",
  fitFormFunction: "Does this affect Fit Form or Function?",
  validationRequired: "Is Validation Testing required?",
  testPlan: "If YES describe test plan:",
  qcProcedure: "QC Procedure to Prevent Mixing Parts:",
  implementationPlan: "Planned Implementation Batch/Date:",
  section4: "SECTION 4: STOCK DISPOSITION (What about old parts?)",
  useAsIs: "Use As-Is",
  scrap: "Scrap",
  rework: "Rework",
  notes: "Notes",
  rawMaterial: "Raw Material:",
  wip: "WIP (In Process):",
  finishedGoods: "Finished Goods:",
  section7: "SECTION 7: LINKS, TRAINING, AND IMPACT",
  affectedDrawing: "Affected Drawing:",
  affectedDocument: "Affected Document:",
  affectedProcess: "Affected Process:",
  trainingRequired: "Training Required?",
  trainingReference: "Training Reference:",
  customerNotice: "Customer Notification Required?",
  ppapImpact: "PPAP or Validation Impact?",
  section5: "SECTION 5: AUTHORIZATION",
  managerSign: "DMA Engineering/Quality Manager:",
  signDate: "Date:",
  supplierSign: "Supplier Representative (If Applicable):",
  section6: "SECTION 6: VERIFICATION OF IMPLEMENTATION",
  implemented: "Did the change occur successfully on the planned batch?",
  verifiedBy: "Verified By:",
};
